# Catch an exception

# Input:

# Output:
# #runtime_error#

# Exit: 0

# Program:

begin
  try
  	int x = 5/0
  catch (exception x)
	println x
  end
end
